# Generated by Django 5.1 on 2024-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='Краткое описание новости'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='text',
            field=models.TextField(verbose_name='Новости'),
        ),
    ]
